name: Build Windows Installer Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # Allows manual triggering
    inputs:
      build-config:
        description: 'Build Configuration'
        type: choice
        options:
          - Release
          - Debug
        default: 'Release'
      platform:
        description: 'Target Platform'
        type: choice
        options:
          - x64
          - x86
        default: 'x64'

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  build-installer:
    runs-on: windows-latest
    env:
      SOLUTION_FILE: 'SeleniumDemo.sln'  # Update to your solution file
      INSTALLER_PROJECT: 'SetupJobCrawlerWindowsApplication\SetupJobCrawlerWindowsApplication.vdproj'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Visual Studio
        uses: actions/setup-vs@v1
        with:
          vs-version: '17.0'  # VS 2022

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Install VS Installer Projects
        run: |
          # Find VSIXInstaller path (VS 2022 default location)
          $vsixPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe"
          
          # Download the extension
          $vsixUrl = "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/VisualStudioClient/vsextensions/MicrosoftVisualStudio2017InstallerProjects/1.0.0/vspackage"
          $installer = "$env:RUNNER_TEMP\VSInstallerProjects.vsix"
          Invoke-WebRequest -Uri $vsixUrl -OutFile $installer
          
          # Install with full path
          & "$vsixPath" /q /a $installer

      - name: Build installer
        run: |
          msbuild "$env:INSTALLER_PROJECT" `
            /p:Configuration=${{ github.event.inputs.build-config || 'Release' }} `
            /p:Platform=x64 `
            /p:DeployOnBuild=true `
            /p:CreatePackageOnPublish=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: SetupJobCrawlerWindowsApplication\${{ github.event.inputs.build-config || 'Release' }}/*.msi