name: Build Windows Installer Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # Allows manual triggering
    inputs:
      build-config:
        description: 'Build Configuration'
        type: choice
        options:
          - Release
          - Debug
        default: 'Release'
      platform:
        description: 'Target Platform'
        type: choice
        options:
          - x64
          - x86
        default: 'x64'

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  build-installer:
    runs-on: windows-latest
    env:
      SOLUTION_FILE: 'SeleniumDemo.sln'  # Update to your solution file
      INSTALLER_PROJECT: 'SetupJobCrawlerWindowsApplication\SetupJobCrawlerWindowsApplication.vdproj'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
           ls ${{ github.workspace }}
      - name: Verify project file exists
        run: |
          $projectPath = "SetupJobCrawlerWindowsApplication\SetupWindowsApplication.vdproj"
          if (-not (Test-Path $projectPath)) {
              Write-Error "Project file not found at: $projectPath"
              Get-ChildItem -Recurse -Include *.vdproj
              exit 1
          }
          echo "PROJECT_PATH=$projectPath" >> $env:GITHUB_ENV

      - name: Install VS Installer Projects Extension
        run: |
          $vsixUrl = "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/VisualStudioClient/vsextensions/MicrosoftVisualStudio2017InstallerProjects/1.0.0/vspackage"
          $installer = "$env:RUNNER_TEMP\VSInstallerProjects.vsix"
          Invoke-WebRequest -Uri $vsixUrl -OutFile $installer
          
          $vsixInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe"
          & "$vsixInstaller" /q /a $installer

      - name: Build installer
        run: |
          $msbuild = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          & "$msbuild" "$env:PROJECT_PATH" `
            /p:Configuration=${{ github.event.inputs.build-config || 'Release' }} `
            /p:Platform=x64 `
            /p:DeployOnBuild=true `
            /p:CreatePackageOnPublish=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: SetupJobCrawlerWindowsApplication\${{ github.event.inputs.build-config || 'Release' }}/*.msi