# This workflow will build a .NET project  
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net  

name: .NET  

on:
    push:  
        branches: [ "master" ]  
    pull_request:  
        branches: [ "master" ]  

permissions:
 contents: write
 actions: write

jobs:  
 Build-test-and-publish-test:

  runs-on: windows-latest
  steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
       - name: Check out repository code
         uses: actions/checkout@v4
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "🖥 The workflow is now ready to test your code on the runner."
       - name: List files in the repository
         run: |
           ls ${{ github.workspace }}
       - run: echo " This job's status is ${{ job.status }}."
       - name: Setup dotnet
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 9.0.x
       - name: Install dependencies
         run: dotnet restore
       - name : Build
         run: dotnet build
       - name:  Create a tool manifest
         run: dotnet new tool-manifest
       - name:  install DotnetCrtfJsonReporter as local tool
         run: dotnet tool install DotnetCtrfJsonReporter --local
       - name: Test with dotnet, create trx file
         run: dotnet test --logger "trx;logfilename=testResults.trx" --filter "Category!=live"
         if: always()
       - name: List files in the repository
         if: always()
         run: |
           ls ${{ github.workspace }}
       - name: run DotNetCrtfJsonReporter to convert TRX file into a CTRF
         if: always()
         run: dotnet tool run DotnetCtrfJsonReporter -p "WebCrawlerTests/TestResults/testResults.trx"
       - name: List files in the repository
         if: always()
         run: |
           ls ${{ github.workspace }}
       - name: Publish Test Summary Results
         if: always()
         run: npx github-actions-ctrf ctrf/ctrf-report.json
