name: Build Windows Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  actions: write

jobs:
  build-and-package:
    runs-on: windows-latest  # Changed to Windows runner for Windows app builds
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Release version
      run: dotnet build --configuration Release
      
    - name: Publish as self-contained
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
      
    - name: Create MSIX package (optional)
      run: |
        # Only works for MAUI/WinUI projects with proper packaging setup
        dotnet publish -c Release -f net9.0-windows10.0.19041.0 -p:GenerateAppxPackageOnBuild=true
        
    - name: Zip artifacts
      run: |
        $outputDir = "$env:GITHUB_WORKSPACE\artifacts"
        New-Item -ItemType Directory -Path $outputDir -Force
        
        # Zip the published app
        Compress-Archive -Path "$env:GITHUB_WORKSPACE\bin\Release\net9.0-windows10.0.19041.0\win-x64\publish\*" -DestinationPath "$outputDir\Application.zip"
        
        # If MSIX was created, include it
        if (Test-Path "$env:GITHUB_WORKSPACE\bin\Release\net9.0-windows10.0.19041.0\win-x64\AppPackages\*") {
          Copy-Item -Path "$env:GITHUB_WORKSPACE\bin\Release\net9.0-windows10.0.19041.0\win-x64\AppPackages\*" -Destination $outputDir -Recurse
        }
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-artifacts
        path: ${{ github.workspace }}/artifacts/
        
    # Optional: Test execution (if you have tests)
    - name: Run tests
      run: dotnet test --logger "trx;logfilename=testResults.trx"
      if: always()
      
    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ github.workspace }}/**/*.trx