name: Build WPF Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-package:
    runs-on: windows-latest  # Required for WPF builds
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Release version
      run: dotnet build --configuration Release -p:Platform=x64
      
    - name: Publish as self-contained
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:Platform=x64
      
    - name: Create Setup Package (Inno Setup)
      uses: ammaraskar/setup-innosetup@v1
      with:
        version: '6.2.2'
        
    - name: Compile Inno Setup installer
      run: |
        # Create a basic ISS file if none exists
        if (-not (Test-Path "setup.iss")) {
          @"
            [Setup]
            AppName=MyWpfApp
            AppVersion=1.0
            DefaultDirName={pf}\MyWpfApp
            DefaultGroupName=MyWpfApp
            OutputDir=.\artifacts
            OutputBaseFilename=MyWpfApp-Setup
            Compression=lzma
            SolidCompression=yes

            [Files]
            Source: "bin\Release\net9.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

            [Icons]
            Name: "{group}\My WPF App"; Filename: "{app}\MyWpfApp.exe"
            "@ | Out-File -FilePath "setup.iss" -Encoding utf8
                    }
        
                    iscc setup.iss
      
                - name: Upload artifacts
                  uses: actions/upload-artifact@v4
                  with:
                    name: wpf-artifacts
                    path: |
                      bin\Release\net9.0-windows\win-x64\publish\
                      artifacts\*.exe