name: Build and Deploy WPF Application

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build WPF Application (Release)
      run: |
        dotnet build "SetupJobCrawlerWindowsApplication.sln" --configuration Release -p:Platform=x64 -p:DeployOnBuild=true -p:PublishProfile=FolderProfile
        
    - name: Build Deployment Project
      run: |
        # Build the setup project (assuming it's a Visual Studio Installer Project)
        msbuild "SetupJobCrawlerWindowsApplication\SetupJobCrawlerWindowsApplication.vdproj" /p:Configuration=Release /p:Platform=x64
        
    - name: Create artifacts directory
      run: mkdir artifacts
      
    - name: Copy deployment files
      run: |
        copy "SetupJobCrawlerWindowsApplication\Release\SetupJobCrawlerWindowsApplication.msi" artifacts\
        copy "SetupJobCrawlerWindowsApplication\Release\SetupJobCrawlerWindowsApplication.exe" artifacts\
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: artifacts\*
        
    - name: Deploy to Test Environment (Optional)
      if: github.ref == 'refs/heads/master'
      run: |
        # Add your deployment commands here, for example:
        # msiexec /i "artifacts\SetupJobCrawlerWindowsApplication.msi" /quiet
        # Or deploy to a file share:
        copy artifacts\* \\server\deployments\JobCrawler\ /Y
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}